const $=id=>document.getElementById(id);let selected=null,url=null,items=[];
$('file').onchange=()=>{if($('file').files[0])choose($('file').files[0])};
$('drop').ondragover=e=>{e.preventDefault();$('drop').style.background='var(--cream2)'};
$('drop').ondragleave=()=>$('drop').style.background='var(--cream)';
$('drop').ondrop=e=>{e.preventDefault();$('drop').style.background='var(--cream)';if(e.dataTransfer.files[0])choose(e.dataTransfer.files[0])};
function choose(file){if(!file.type.startsWith('image/'))return;selected=file;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);$('preview').src=url;$('preview').style.display='block';$('placeholder').style.display='none';$('chosen').textContent=file.name;$('filename').value=file.name.replace(/\.[^/.]+$/,'')}
$('form').onsubmit=e=>{e.preventDefault();$('message').textContent='';if(!selected){$('message').textContent='Please choose an image.';return}if(!$('title').value.trim()||!$('category').value||!$('description').value.trim()){$('message').textContent='Complete all required fields.';return}let ext=selected.name.match(/\.[^/.]+$/)?.[0]||'.png';items.unshift({url,filename:($('filename').value||'image')+ext,title:$('title').value,category:$('category').value,price:Number($('price').value)||0,description:$('description').value});selected=null;url=null;$('form').reset();$('preview').style.display='none';$('placeholder').style.display='block';$('chosen').textContent='';$('message').style.color='#5a2a91';$('message').textContent='Image uploaded successfully.';render()};
$('search').oninput=render;$('filter').onchange=render;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){let q=$('search').value.toLowerCase(),f=$('filter').value,a=items.filter(x=>(f==='All'||x.category===f)&&(x.title.toLowerCase().includes(q)||x.filename.toLowerCase().includes(q)));$('gallery').innerHTML=a.length?a.map(x=>{let i=items.indexOf(x);return `<article class="card"><img src="${x.url}" alt="${esc(x.title)}"><div><h3>${esc(x.title)}</h3><small>${esc(x.filename)}</small><br><span class="tag">${esc(x.category)}</span><p>${esc(x.description)}</p><small>Price metadata: ₱${x.price.toFixed(2)}</small><br><button class="delete" data-i="${i}">Delete</button></div></article>`}).join(''):'<div class="empty"><h3>No images yet</h3><p>Upload your first image to begin.</p></div>';document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;URL.revokeObjectURL(items[i].url);items.splice(i,1);render()})}
render();